import { type z } from 'zod';

import { environmentSchema } from './environment-schema';

interface VariableMetadata {
  readonly description?: string;
  readonly example?: string;
}

interface SchemaDefinition {
  readonly type?: string;
  readonly defaultValue?: unknown;
  readonly innerType?: z.ZodType;
}

/**
 * Zod wraps a schema once per modifier, so a field carrying both `.default()`
 * and `.meta()` is several layers deep. Walking the chain iteratively keeps the
 * traversal obvious and bounded.
 */
function unwrapSchemaChain(schema: z.ZodType): z.ZodType[] {
  const chain: z.ZodType[] = [];
  let current: z.ZodType | undefined = schema;

  while (current !== undefined) {
    chain.push(current);
    current = (current.def as SchemaDefinition).innerType;
  }

  return chain;
}

function readDefaultValue(schema: z.ZodType): string | undefined {
  for (const link of unwrapSchemaChain(schema)) {
    const definition = link.def as SchemaDefinition;
    if (definition.type !== 'default' || definition.defaultValue === undefined) {
      continue;
    }
    const { defaultValue } = definition;
    if (typeof defaultValue === 'string') {
      return defaultValue;
    }
    if (typeof defaultValue === 'number' || typeof defaultValue === 'boolean') {
      return String(defaultValue);
    }
  }
  return undefined;
}

function readMetadata(schema: z.ZodType): VariableMetadata {
  for (const link of unwrapSchemaChain(schema)) {
    const metadata = link.meta() as VariableMetadata | undefined;
    if (metadata !== undefined) {
      return metadata;
    }
  }
  return {};
}

/**
 * Renders `.env.example` from the schema, so the documented variables are by
 * construction the variables the application validates. A test compares the
 * committed file against this output.
 */
export function generateEnvironmentExample(): string {
  const lines: string[] = [
    '# Generated by "pnpm generate:env-example".',
    '# Edit packages/configuration/src/environment-schema.ts instead of this file.',
    '',
  ];

  const shape = environmentSchema.shape as Record<string, z.ZodType>;

  for (const [variableName, fieldSchema] of Object.entries(shape)) {
    const metadata = readMetadata(fieldSchema);
    const defaultValue = readDefaultValue(fieldSchema);

    if (metadata.description !== undefined) {
      lines.push(`# ${metadata.description}`);
    }
    if (defaultValue === undefined) {
      lines.push('# Required.');
    }

    lines.push(`${variableName}=${defaultValue ?? metadata.example ?? ''}`, '');
  }

  return lines.join('\n');
}
