import { type z } from 'zod';

import { environmentSchema } from './environment-schema';

interface VariableMetadata {
  readonly description?: string;
  readonly example?: string;
}

interface SchemaDefinition {
  readonly type?: string;
  readonly defaultValue?: unknown;
  readonly innerType?: z.ZodType;
  /** A `.transform()` produces a pipe whose input side holds the default. */
  readonly in?: z.ZodType;
}

/**
 * Zod wraps a schema once per modifier, so a field carrying `.default()`,
 * `.transform()` and `.meta()` is several layers deep. Both wrapper shapes have
 * to be followed: modifiers such as `.default()` nest under `innerType`, while
 * `.transform()` produces a pipe whose input side is where an earlier default
 * lives.
 */
function unwrapSchemaChain(schema: z.ZodType): z.ZodType[] {
  const chain: z.ZodType[] = [];
  const pending: z.ZodType[] = [schema];

  while (pending.length > 0) {
    const current = pending.pop();
    if (current === undefined) {
      break;
    }
    chain.push(current);

    const definition = current.def as SchemaDefinition;
    if (definition.innerType !== undefined) {
      pending.push(definition.innerType);
    }
    if (definition.in !== undefined) {
      pending.push(definition.in);
    }
  }

  return chain;
}

function readDefaultValue(schema: z.ZodType): string | undefined {
  for (const link of unwrapSchemaChain(schema)) {
    const definition = link.def as SchemaDefinition;
    if (definition.type !== 'default' || definition.defaultValue === undefined) {
      continue;
    }
    const { defaultValue } = definition;
    if (typeof defaultValue === 'string') {
      return defaultValue;
    }
    if (typeof defaultValue === 'number' || typeof defaultValue === 'boolean') {
      return String(defaultValue);
    }
  }
  return undefined;
}

function readMetadata(schema: z.ZodType): VariableMetadata {
  for (const link of unwrapSchemaChain(schema)) {
    const metadata = link.meta() as VariableMetadata | undefined;
    if (metadata !== undefined) {
      return metadata;
    }
  }
  return {};
}

/**
 * Renders `.env.example` from the schema, so the documented variables are by
 * construction the variables the application validates. A test compares the
 * committed file against this output.
 */
export function generateEnvironmentExample(): string {
  const lines: string[] = [
    '# Generated by "pnpm generate:env-example".',
    '# Edit packages/configuration/src/environment-schema.ts instead of this file.',
    '',
  ];

  const shape = environmentSchema.shape as Record<string, z.ZodType>;

  for (const [variableName, fieldSchema] of Object.entries(shape)) {
    const metadata = readMetadata(fieldSchema);
    const defaultValue = readDefaultValue(fieldSchema);

    if (metadata.description !== undefined) {
      lines.push(`# ${metadata.description}`);
    }
    if (defaultValue === undefined) {
      lines.push('# Required.');
    }

    lines.push(`${variableName}=${defaultValue ?? metadata.example ?? ''}`, '');
  }

  return lines.join('\n');
}
